import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-gray-400 bg-gray-300 body-font h-screen overflow-hidden">
        <Header />
        <section>
      <div className="container mx-auto flex px-10 py-20 md:flex-row flex-col items-center">
        <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
          <h1 className="text-3xl font-extrabold leading-9 tracking-tight text-gray-800 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">
            Microfrontends,{' '}
            <br className="hidden lg:inline-block" />pretty neat stuff.
          </h1>
          <div className="my-4 border-b-[12px] border-blue-500 w-[4rem]"></div>
          <p className="mb-8 leading-relaxed text-gray-600">
            Independently deployed, scalable, smaller & more manageable. 
            What&apos;s not to love?
          </p>
        </div>
        <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
          {/* <img
            className="object-contain object-center rounded"
            alt="hero"
            src="/dog.png"
          /> */}
        </div>
      </div>
    </section>
    </main>
    </div>
  )
}
